### PR TITLE
Upgrade to Angular 10

### LINKED ISSUE #86: Upgrade to support Angular 10

### PR DESCRIPTION
**Pull request by davidshen84**
Resolve #86 

- ng test, pass
- ng e2e, pass

### CODE REVIEW

**Comment by basst314** [comment]
Hi @davidshen84,

Thanks for collaborating on this project and raising this pr!
I‘ve noticed that the CI build has failed, can you take a look?
Also, I want to do some additional testing to verify that the lib still gets bundled correctly and want to try using it in one of my demo projects for testing before release.
Thanks!

**Comment by davidshen84** [comment]
Hi @basst314,

I have fixed the build issue and the PR passed the CI. The problem is
caused by the browserslist package. I have updated it to 4.12.0 to resolve
the issue.


Thanks,
David

**Comment by shubhamt619** [comment]
@davidshen84  @basst314  Thanks for Angular 10 support ! ! 
Great Job

**Comment by guyenot-jeremy** [comment]
Hi @basst314 could you please merge this PR?

**Comment by rlyttle** [comment]
@basst314 Thanks for your great work on this project! I'd really love this PR to be merged, I can't upgrade my angular app without it!

**Comment by hisham** [comment]
+1.

**Comment by ccaseauSAG** [comment]
+1

**Comment by hisham** [comment]
Just to add more clarification, the existing package works fine in angular 10. We just need this PR merged to remove some warnings.

**Pull request merged**
