### PR TITLE
Pause video to prevent mobile browser freezes onDestroy

### PR DESCRIPTION
**Pull request by JemiloII**

### CODE REVIEW

**Comment by jmeinke** [comment]
@basst314 Please merge this and release a new version!

**Comment by kishoreaoe** [comment]
@JemiloII , will this PR, solves in browser slowness when we load the video element multiples times, as this is happening because we are not destroying it completely on changing to new route.

**Comment by kishoreaoe** [comment]
@basst314 , kindly help in merging this PR, this is very much useful

**Comment by JemiloII** [comment]
When the component is unloaded, the video is component is destroyed on its own. However, not stopping the video play while destroying the video element causes problems that ends up freezing the browser.

**Comment by kishoreaoe** [comment]
@JemiloII , any other workaround to implement the same, if new version is not released.

**Pull request merged**
